title: "Lo先生的博客"
description: "L先生的博客,一个有趣而精彩的地方。"
url: "https://leliang-sjtu.github.io/" 
author: "Lo"
author_image: "https://leliang-sjtu.github.io/assets/images/avatar.jpg"
social_links:  
  github: "https://github.com//LeLiang-SJTU"  
#theme: minima

#source: docs  # 指定
collections_dir: docs

#使用集合


#collections_dir: docs
collections:
  books:
    output: true
    permalink: /books/:path/

# Navigation settings
navigation:
  - title: 首页
    url: /
  - title: 技术
    url: /tech
  - title: 生活
    url: /life
  - title: GIthub项目
    url: /githubs
  - title: 关于
    url: /about

markdown: kramdown
kramdown:
  input: GFM                # 使用 GitHub Flavored Markdown 语法
  syntax_highlighter: rouge  # 使用 rouge 代码高亮
  hard_wrap: false          # 禁止自动换行（保持原格式）
  # 添加以下配置强制启用表格和代码块支持
  parse_block_html: true
  parse_span_html: true
  auto_ids: true
  enable_coderay: false     # 如果使用 rouge，需关闭 coderay

# Add default front matter for all pages
defaults:
  - scope:
      path: ""      # Apply to all files
      type: "posts" # Apply to posts
    values:
      toc: true     # Enable TOC by default

plugins:
  - jekyll-toc